config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # root to: 'admin/entries#index'
  root to: 'quest#index'


  get 'scrape', to: 'scraper#scrape', as: 'scrape'

  post 'quest', to: 'quest#validate', as: :post_quest

end

app/views/quest/index.html.erb
<header>
  <h1>Roundie Challenge</h1>
  <h2>In Search of the Unknown</h2>
</header>


<!--<audio id="audio-noti" src="<%#= asset_path('clue.mp3') %>" preload="auto"></audio>-->
<!--<audio id="audio-kwi" src="<%#= asset_path('kwi.mp3') %>" preload="auto"></audio>-->

<!--<audio id="audio-gpaul" src="<%#= asset_path('gpaul.mp3') %>" preload="auto"></audio>-->
<!--<audio id="audio-gpol" src="<%#= asset_path('gpol.mp3') %>" preload="auto"></audio>-->
<!--<audio id="audio-wisely" src="<%#= asset_path('wisely.mp3') %>" preload="auto"></audio>-->
<!--<audio id="audio-poorly" src="<%#= asset_path('poorly.mp3') %>" preload="auto"></audio>-->

<div class="containers-frame">

  <div class="clue">
    <% if @clue&.clue.present? %>
      <%= @clue.priority %>. <%= @clue.clue.gsub('\n', '<br>').html_safe %>
    <% else %>
      Muy bien Flancito, terminaste el Roundie challenge!
    <% end %>
  </div>


  <%= form_for :quest, url: post_quest_path, method: :post do |form| %>
    <div class="inputs-container">

      <input name="l1" maxlength="1">
      <input name="l2" maxlength="1">
      <input name="l3" maxlength="1">

      <input name="l4" maxlength="1">
      <input name="l5" maxlength="1">
      <input name="l6" maxlength="1">
    </div>



    <% unless @error.nil? %>
      <% if @error %>
        <div class="notification"><%= @error_message %></div>
        <audio autoplay>
          <source src="<%= asset_path('clown.mp3') %>" type="audio/mp3">
        </audio>
      <% else %>
        <div class="notification success"><%= @error_message %></div>
        <audio autoplay>
          <source src="<%= asset_path('wisely.mp3') %>" type="audio/mp3">
        </audio>
      <% end %>
    <% end %>
    <%= form.submit(:value => "Validar Código") %>
  <% end %>


</div>